services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: sourav
      POSTGRES_PASSWORD: sourav
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - jobstore-network
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@mail.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-sourav}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - jobstore-network
    restart: unless-stopped

networks:
  jobstore-network:
    driver: bridge

volumes:
  postgres:
  pgadmin: